# Save paths
checkpoint_save_dir: 'results/checkpoints'
gifs_save_dir: 'results/gifs'

# Enviroment settings
env_name: ModifiedDungeon
env_class: !name:enviroment.ModifiedDungeon
env_config:
  width: 20
  height: 20
  max_rooms: 3
  min_room_xy: 5
  max_room_xy: 10
  observation_size: 11
  vision_radius: 5
  max_steps: 1000

# Model settings
kernel: !tuple (3, 3)
model:
  conv_filters: [
    [ 16, !ref <kernel>, 2 ],
    [ 32, !ref <kernel>, 2 ],
    [ 32, !ref <kernel>, 1 ],
  ]
  post_fcnet_hiddens: [ 32 ]
  post_fcnet_activation: "relu"
  vf_share_layers: False

# Agent config
agent_config:
  num_gpus: 1
  log_level: "INFO"
  framework: "torch"
  env: !ref <env_name>
  env_config: !ref <env_config>
  model: !ref <model>
  rollout_fragment_length: 100
  entropy_coeff: 0.1
  lambda: 0.95
  vf_loss_coeff: 1.0

agent: !name:ray.rllib.agents.ppo.PPOTrainer
#  config: !ref <agent_config> broken because we need to register env

# Learning configs
n_iters: 200

# Eval
eval_steps: 500